# <center> Homework 1 </center>

# 0. Где мы сейчас?
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Jupyter_logo.svg/1200px-Jupyter_logo.svg.png" width="150">

[Jupyter Notebook](https://jupyter.org/) - интерактивная среда для запуска программного кода в браузере. Удобный инструмент для анализа данных, который используется многими специалистами по data science. Позволяет выполнять отдельные ячейки с кодом, а не всю программу сразу, что очень удобно при знакомстве с данными.

# 1. Python
> Python - это свободный интерпретируемый объектно-ориентированный расширяемый встраиваемый язык программирования очень высокого уровня 

>*(Г.Россум, Ф.Л.Дж.Дрейк, Д.С.Откидач "Язык программирования Python").*

А если без цитат, то питон - это просто очень крутой язык, созданный в 1991 году [Великодушным пожизненным диктатором](https://ru.wikipedia.org/wiki/%D0%92%D0%B5%D0%BB%D0%B8%D0%BA%D0%BE%D0%B4%D1%83%D1%88%D0%BD%D1%8B%D0%B9_%D0%BF%D0%BE%D0%B6%D0%B8%D0%B7%D0%BD%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9_%D0%B4%D0%B8%D0%BA%D1%82%D0%B0%D1%82%D0%BE%D1%80) Гвидо ван Россумом и названный в честь любимого им шоу [Monty Python's Flying Circus](https://en.wikipedia.org/wiki/Monty_Python%27s_Flying_Circus)

<img src="https://advancelocal-adapter-image-uploads.s3.amazonaws.com/image.oregonlive.com/home/olive-media/width2048/img/tv/photo/2018/10/10/montycastjpg-7ef393e2355a42aa.jpg" width="300">

# 2. Anaconda

<img src="https://cdn-images-1.medium.com/max/1600/0*MVkCW8_Bmj-nuAnI.png" width="300">

[Сборка Anaconda](https://www.anaconda.com/products/individual) включает очень много полезных библиотек для анализа данных. 

Среди наиболее популярных библиотек:
 - <a href="http://numpy.org">Numpy</a> - это один из основных пакетов для математических вычислений. Он содержит средства для работы с многомерными массивами и высокоуровневыми математическими функциями
 - <a href="https://www.scipy.org/">SciPy</a> - научные вычисления. Методы оптимизации, интегрирования, модули обработки сигналов и изображений, статистика, линейная алгебра, сплайны, кластеризация и многое другое
 -  <a href="http://pandas.pydata.org/">Pandas</a> - основная библиотека для обработки и анализа данных. Предназначена для данных разной природы - матричных, панельных данных, временных рядов. Претендует на звание самого мощного и гибкого средства для анализа данных с открытым исходным кодом
 - <a href="http://scikit-learn.org/stable/">Scikit-learn</a> - реализация очень многих методов машинного обучения с отличной документацией. 
 - <a href="http://http://matplotlib.org/">matplotlib</a> - хорошая библиотека для визуализации данных

# 3. Задачки

## Задача 1
$N$ хоббитов делят $K$ кусков эльфийского хлеба поровну, не делящийся нацело остаток остается в корзинке у Сэма. Напишите функцию, которая принимает на вход параметры $N$ и $K$ и возвращает два числа: $x$ - cколько кусков эльфиского хлеба достанется каждому хоббиту, и $y$ - сколько кусков остаётся в корзинке.

In [1]:
def share_bread(N, K):
    # your code here
    if (not(isinstance(N,int)) or N<=0):
        print(f'Warning: Некорректное количество хоббитов: {N}. Для корректного расчета требуется целое положительное количество хоббитов.')
        return -1, K
    x = K//N
    y = K-x*N
    return x, y

# если в функции всё верно, то после выполнения этой строчки, не должно выскакивать ошибок
assert share_bread(N=3, K=14) == (4, 2)

# доп проверки
assert share_bread(0, K=14) == (-1, 14)
assert share_bread(2.5, K=14) == (-1, 14)
assert share_bread(-4, K=14) == (-1, 14)
assert share_bread(5, K=4) == (0, 4)

## Задача 2

В копях Мории хоббиты нашли стену, на которой высечены разные натуральные числа. Согласно древним сказаниям, это даты сражений. Хоббиты знают, что сражения происходили только по високосным годам. Помогите хоббитам определить, является ли год с данным числом датой великого сражения. Если это так, то верните строку "YOU SHALL PASS", иначе верните "YOU SHALL NOT PASS". Напомним, что в соответствии с хоббитским календарем, год является високосным, если его номер кратен 4, но не кратен 100, а также если он кратен 400.

In [2]:
def leap_year(year):
    # your code here
    text_result = 'YOU SHALL PASS' if (year%4 == 0 and year%100 != 0 or year%400 == 0 ) else 'YOU SHALL NOT PASS'
    return text_result

assert leap_year(5) == 'YOU SHALL NOT PASS'

# доп проверки
assert leap_year(3) == 'YOU SHALL NOT PASS'
assert leap_year(4) != 'YOU SHALL NOT PASS'
assert leap_year(96) != 'YOU SHALL NOT PASS'
assert leap_year(97) == 'YOU SHALL NOT PASS'
assert leap_year(99) == 'YOU SHALL NOT PASS'
assert leap_year(100) == 'YOU SHALL NOT PASS'
assert leap_year(104) != 'YOU SHALL NOT PASS'
assert leap_year(196) != 'YOU SHALL NOT PASS'
assert leap_year(200) == 'YOU SHALL NOT PASS'
assert leap_year(400) != 'YOU SHALL NOT PASS'
assert leap_year(800) != 'YOU SHALL NOT PASS'
assert leap_year(900) == 'YOU SHALL NOT PASS'
assert leap_year(1200) != 'YOU SHALL NOT PASS'
assert leap_year(2000) != 'YOU SHALL NOT PASS'

## Задача 3
<img src="http://i0.kym-cdn.com/photos/images/original/001/187/255/5e9.gif" width=300>
Для могущественного магического ритуала Гендальфу необходимо быстро подсчитывать площадь своего амулета, который умеет менять размеры. Известно, что амулет имеет форму треугольника и Гендальф знает длину каждой из сторон. Напишите функцию, которая считает площадь амулета по трем сторонам.  

Подсказка: используйте формулу Герона
$$ S = \sqrt{p(p-a)(p-b)(p-c)} $$
$$ p = \frac{a + b + c}{2}$$


In [3]:
def amulet_area(a, b, c):
    # your code here
    # функция определения корректности входящего значения
    check_real = lambda leg: (isinstance(leg, (float, int)) and leg > 0)
    # определяем количество корректных в списке
    check_result = filter(check_real, (a,b,c))
    if (len(list(check_result)) != 3):
        print(f'Warning: Некорректные длины строн: {a}, {b}, {c}. Для корректного расчета требуется числовые положительное значения сторон.')
        return -1
    
    P = (a + b + c)/2
    S = (P * (P-a) * (P-b) * (P-c)) ** 0.5
    return S

assert amulet_area(3, 4, 5) == 6

# доп проверки
assert amulet_area(6, 8, 10) == 24
assert amulet_area(-1, 8, 10) == -1
assert amulet_area(6, 0, 10) == -1
assert amulet_area(6, 0, 'c') == -1

## Задача 4

Хоббиты собираются пешком идти до Мордора и им нужно подсчитать расстояние, которое им предстоит пройти. Хоббиты смогли вспомнить сразу несколько метрик расстояния: евклидово, манхэттена и косинусное, так что ваша задача - напистаь функцию под каждую из них. Важное условие - используйте только базовые функции numpy для решения.


* Евклидово расстояние
$$ d(a, b) = \sqrt{\sum_i (a_i - b_i)^2} $$
* Расстояние Манхэттена
$$ d(a, b) = \sum_i |a_i - b_i| $$
* Косинусное расстояние
$$ d(a, b) = 1 - \frac{a^\top b}{||a||_2\cdot||b||_2}$$

In [4]:
import numpy as np
def cal_euclidean(a, b):
    ## Your code here
    a = np.array(a)
    b = np.array(b)
    distance = np.sum(np.square(a - b)) ** 0.5
    return distance


def cal_manhattan(a, b):
    ## Your code here
    # print(f'------\n', np.abs(np.array(a) - np.array(b)))
    a = np.array(a)
    b = np.array(b)
    distance = np.sum(np.abs(a - b))
    return distance


def cal_cosine(a, b):
    ## Your code here
    # Скалярное произведение векторов
    a = np.array(a)
    b = np.array(b)
    scal_pr = np.sum(a * b)

    distance = 1 - abs(scal_pr) / (sum(np.square(a)) ** 0.5 * sum(np.square(b)) ** 0.5)  # Диапазон [0 , 1]
    # distance = 1 - scal_pr / (sum(np.square(a)) ** 0.5 * sum(np.square(b)) ** 0.5)  # Диапазон [0 , 2]
    return distance

In [5]:
a = np.random.randint(-10, 10, size=10)
b = np.random.randint(-10, 10, size=10)
print(cal_euclidean(a, b))
print(cal_manhattan(a, b))
print(cal_cosine(a, b))

27.622454633866266
77
0.8925978549482732


## Задача 5

Ну и напоследок, еще немного практики numpy, без которой не обходится ни один хоббит.


Создайте случайный array (`np.random.rand()`) длинной 100. Преобразуйте его так, чтобы
* Максимальный элемент(ы) был равен 1
* Минимальный элемент(ы) был равен 0
* Остальные элементы в итнтервале от 0 до 1 остаются прежними

In [6]:
my_array = np.random.rand(100)
## Your code here
my_array[np.argmax(my_array)] = 1
my_array[np.argmin(my_array)] = 0
print(np.max(my_array), np.min(my_array))
print(my_array)

1.0 0.0
[0.33947562 0.33205245 0.32948545 0.32771979 0.38531536 0.36666908
 0.14814159 0.31115951 0.23348894 0.75848819 0.12771692 0.72716592
 0.99059075 0.75805092 0.52410939 0.1891428  0.39149334 1.
 0.         0.49574372 0.67696638 0.29497392 0.77647427 0.18597958
 0.16057342 0.06296158 0.66870618 0.96265275 0.4724932  0.9087026
 0.60523574 0.13200208 0.88685338 0.92070787 0.58351691 0.10133378
 0.54151895 0.64933462 0.16690033 0.6553931  0.60372646 0.01936525
 0.17600667 0.1136696  0.20482999 0.11799381 0.65118676 0.01447857
 0.42436462 0.59980955 0.79105794 0.04621226 0.35073385 0.67724841
 0.72704365 0.86698831 0.85477655 0.36766954 0.38104125 0.12466322
 0.45177737 0.94398869 0.70566399 0.27855934 0.42878529 0.76450211
 0.68793959 0.80573144 0.17217883 0.43798559 0.98623337 0.69391078
 0.55736368 0.35600699 0.34102699 0.10041877 0.71402824 0.4451603
 0.83078551 0.15061167 0.0574692  0.30762935 0.04224599 0.68643077
 0.43261247 0.21060799 0.9013415  0.96077013 0.94425327 0.397880

Создайте array размером $5 \times 6$ с целыми числами в интервале [0,50]. Напечатайте колонку, которая содержит максимальный элемент полученной матрицы 

In [7]:
my_array = np.random.randint(0, 51, size = (5, 6))
## Your code here
max_index = np.argmax(my_array)
max_index_list = divmod(max_index, my_array.shape[1])
# print(max_index_list)
# print(my_array.transpose()[max_index_list[1]])
selected_column = my_array.transpose()[max_index_list[1]]
## Your code here
print('Shape: ',my_array.shape)
print('Array')
print(my_array)
print('Column:', selected_column)

Shape:  (5, 6)
Array
[[17 25  9 41 40 50]
 [19 16 22 10 43 36]
 [35 29 50  5 35 39]
 [13 10 27 39 44 42]
 [37 50 43 42 41 37]]
Column: [50 36 39 42 37]


Напишите функцию, которая принимает на вхoд матрицу (array) X и возвращает все её уникальные строки в виде новой матрицы.

In [8]:
def get_unique_rows(X):
    # Your code here
    X_unique = np.unique(X, axis = 0)
    return X_unique

In [9]:
X = np.random.randint(4, 6, size=(10,3))
print(X)

[[5 4 5]
 [5 5 5]
 [4 4 4]
 [5 4 4]
 [5 4 4]
 [5 5 4]
 [5 5 4]
 [5 4 5]
 [5 5 5]
 [5 4 4]]


In [10]:
get_unique_rows(X)

array([[4, 4, 4],
       [5, 4, 4],
       [5, 4, 5],
       [5, 5, 4],
       [5, 5, 5]])